### ISSUE TITLE
About

### ISSUE THREAD

**Issue by lexadecimals** [fac-12/webify#12]
- [x]  Change or remove heading - decide if use of idioms is acceptable in this instance
- [x]  Write content
- [x]   Add 100vh to desktop view, remove from mobile

**Comment by carolineapp** [comment]
TEXT FOR ABOUT SECTION


Imagine, Build, Test, Repeat.

We are creative, custom web development agency for all of your web requirements.

Responsive

We create with everyone in mind - the pages that we create for you will look fantastic on desktop, tablets and mobile.

We are also responsive to you! From the outset we listen and learn to ensure that the end product is perfect for you.

Inclusive

We have the needs of others at the heart of our projects. Our simple yet elegant solutions are clear to navigate and understand.
