### ISSUE TITLE
Accessibility Improvement 

### ISSUE THREAD

**Issue by trc5019** [fac-12/webify#32]
In order to improve accessibility you could put the nav section within the header tag.
In the outliner 1. comes up as untitled body.

**Comment by jsms90** [comment]
Good spot @trc5019. I wondered about that myself.

But after a bit of googling, I'm not sure it's that cut and dry:
> [Many web designers consider the navigation bar to be part of the header rather than a individual component, but that's not a requirement; in fact some also argue that having the two separate is better for accessibility, as screen readers can read the two features better if they are separate.](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure)

**Comment by lexadecimals** [comment]
we've had a look at recommended sites such as gov.uk and they all appear to have an untitled body, so we're not sure what the solution is here
