### ISSUE TITLE
Aim to have everyone committing an equal amount

### ISSUE THREAD

**Issue by Jen-Harris** [fac-12/webify#35]
At the moment there is a large difference between the number of commits by each member of the team (this may be from working on 1 computer and how you've paired) but try and ensure you are swapping pairs and computers regularly and all contributing the same amount 👍

**Comment by lexadecimals** [comment]
We were swapping partners and doing equal amounts of work, but only using 2 laptops. Will try to also change laptops so that it doesn't look unbalanced.
