### ISSUE TITLE
review contributions 

### ISSUE THREAD

**Issue by jessicasalmon** [fac-12/webify#44]
Hey @DevGrrrl @Dragomirc @caralemony @Gbaja,

Really great work this week :tada:

I wanted to flag up your contribution graph, it's quite uneven. Totally understandable in your first week of pairing, but I strongly suggest that you discuss what led to this at your team stop go continue as it's really important that everyone is contributing equally and that you're swapping machines often enough during pairing. 
<img width="1016" alt="screen shot 2017-10-27 at 11 31 00" src="https://user-images.githubusercontent.com/19147734/32099966-587c69a4-bb0a-11e7-9662-14d8ef8afce3.png">

I'll be around in the afternoon, so if you've any questions around pairing (or anything) - let me know :)

**Comment by Gbaja** [comment]
We were swapping partners and doing equal amounts of work, but only using 2 laptops. Will try to also change laptops so that it doesn't look unbalanced.

**Comment by jessicasalmon** [comment]
Hey @Gbaja - that's really great to hear :) definitely do that, otherwise some people won't have many contributions/ people won't be able to see the work that they did whilst at FAC.
